 /***********************************************************************
 
    Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
    
dspeak is simply a D wrapper for espeak

espeak is Copyright (C) 2005 to 2010 by Jonathan Duddington
email: jonsd@users.sourceforge.net 

dspeak is Copyright (C) 2011 to David Osborne
email: krendilboove@gmail.com

The contents of this file shamelessly stolen from Derelict's shared library loading code,
hence the Boost license.
*/
module dspeak.loaddll;

import std.windows.syserror;
import std.c.windows.windows;

import dspeak.cfuncs;

SharedLib lib;

static this(){
    loadLibs();
}
static ~this(){
    lib.unload();
}
public void loadLibs(){
    lib = new SharedLib();
    lib.load(["espeak_lib.dll"]);
    void bindFunc(void** ptr, string funcName, bool doThrow = true)
    {
        void* func = lib.loadSymbol(funcName, doThrow);
        *ptr = func;
    }
    bindFunc(cast(void**)&espeak_Initialize, "espeak_Initialize");
    bindFunc(cast(void**)&espeak_SetSynthCallback, "espeak_SetSynthCallback");
    bindFunc(cast(void**)&espeak_SetUriCallback, "espeak_SetUriCallback");
    bindFunc(cast(void**)&espeak_Synth, "espeak_Synth");
    bindFunc(cast(void**)&espeak_Synth_Mark, "espeak_Synth_Mark");
    bindFunc(cast(void**)&espeak_Key, "espeak_Key");
    bindFunc(cast(void**)&espeak_Char, "espeak_Char");
    bindFunc(cast(void**)&espeak_SetParameter, "espeak_SetParameter");
    bindFunc(cast(void**)&espeak_GetParameter, "espeak_GetParameter");
    bindFunc(cast(void**)&espeak_SetPunctuationList, "espeak_SetPunctuationList");
    bindFunc(cast(void**)&espeak_SetPhonemeTrace, "espeak_SetPhonemeTrace");
    bindFunc(cast(void**)&espeak_CompileDictionary, "espeak_CompileDictionary");
    bindFunc(cast(void**)&espeak_ListVoices, "espeak_ListVoices");
    bindFunc(cast(void**)&espeak_SetVoiceByName, "espeak_SetVoiceByName");
    bindFunc(cast(void**)&espeak_SetVoiceByProperties, "espeak_SetVoiceByProperties");
    bindFunc(cast(void**)&espeak_GetCurrentVoice, "espeak_GetCurrentVoice");
    bindFunc(cast(void**)&espeak_Cancel, "espeak_Cancel");
    bindFunc(cast(void**)&espeak_IsPlaying, "espeak_IsPlaying");
    bindFunc(cast(void**)&espeak_Synchronize, "espeak_Synchronize");
    bindFunc(cast(void**)&espeak_Terminate, "espeak_Terminate");
    bindFunc(cast(void**)&espeak_Info, "espeak_Info");
}

alias HMODULE SharedLibHandle;

private SharedLibHandle LoadSharedLib(string libName)
{
    return LoadLibraryA(toCString(libName));
}

private void UnloadSharedLib(SharedLibHandle hlib)
{
    FreeLibrary(hlib);
}

private void* GetSymbol(SharedLibHandle hlib, string symbolName)
{
    return GetProcAddress(hlib, toCString(symbolName));
}

private string GetErrorString(){
    return sysErrorString(GetLastError());
}

final class SharedLib
{
public:
    this()
    {
    }

    string name()
    {
        return _name;
    }

    bool isLoaded()
    {
        return (_hlib !is null);
    }

    void load(string[] names)
    {
        if(isLoaded)
            return;

        string[] failedLibs;
        string[] reasons;

        foreach(n; names)
        {
            _hlib = LoadSharedLib(n);
            if(_hlib is null)
            {
                failedLibs ~= n;
                reasons ~= GetErrorStr();
                continue;
            }
            _name = n;
            break;
        }

        if(!isLoaded)
        {
            SharedLibLoadException.throwNew(failedLibs, reasons);
        }
    }

    void* loadSymbol(string symbolName, bool doThrow = true)
    {
        void* sym = GetSymbol(_hlib, symbolName);
        if(doThrow && (sym is null))
            Derelict_HandleMissingSymbol(name, symbolName);

        return sym;
    }

    void unload()
    {
        if(isLoaded)
        {
            UnloadSharedLib(_hlib);
            _hlib = null;
        }
    }

private:
    string _name;
    SharedLibHandle _hlib;
}